// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// //import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD1plIJCOOJlqgVoQXlwJdb5QlvSi_Dz2g',
//     appId: '1:785670252574:web:4682248d50e26eb3b0a60f',
//     messagingSenderId: '785670252574',
//     projectId: 'cato-trivia',
//     authDomain: 'cato-trivia.firebaseapp.com',
//     storageBucket: 'cato-trivia.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAI1ZyFuzNzpkWBEUV0PDoTXHzCUu3th3Q',
//     appId: '1:785670252574:android:88720175e3c082adb0a60f',
//     messagingSenderId: '785670252574',
//     projectId: 'cato-trivia',
//     storageBucket: 'cato-trivia.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAi4IsKRPd5qWH5YYCSq93hGntMKcmTWcE',
//     appId: '1:785670252574:ios:fd7a76a2f3fb8a21b0a60f',
//     messagingSenderId: '785670252574',
//     projectId: 'cato-trivia',
//     storageBucket: 'cato-trivia.appspot.com',
//     iosClientId: '785670252574-ulbffnglahuqtp9jtu43k5oqnrle119r.apps.googleusercontent.com',
//     iosBundleId: 'com.example.catoTrivia',
//   );
// }
